version: "3.9"

services:
  backend:
    # 1. Diubah dari 'image' ke 'build' agar penilai bisa build dari source
    build: ./backend
    container_name: backend-api-sayur
    ports:
      - "5000:5000"
    environment:
      # 2. Diubah agar membaca dari file .env
      - DB_HOST=mysql
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mysql
    networks:
      - sayur-network
    volumes:
      - ./backend/uploads:/app/uploads

  mysql:
    image: mysql:8 # Database boleh tetap pakai image
    container_name: mysql
    restart: always
    environment:
      # 3. Diubah agar membaca dari file .env
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - sayur-network

  frontend:
    # 4. Diubah dari 'image' ke 'build'
    build:
      context: ./frontend
      args:
        # 5. Ini PENTING: Mengirim variabel dari .env ke proses build React
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    container_name: frontend-sayur
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - sayur-network

networks:
  sayur-network:

volumes:
  mysql-data: