version: "3.9"

services:
  backend:
    image: felixmaicleine/sayur-backend:latest
    container_name: backend-api-sayur
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=db_sayur
      - JWT_SECRET=supersecretkey
    depends_on:
      - mysql
    networks:
      - sayur-network
    volumes:
      - ./backend/uploads:/app/uploads

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=db_sayur
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - sayur-network

  frontend:
    image: felixmaicleine/sayur-frontend:latest
    container_name: frontend-sayur
    restart: always
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://34.143.168.92:5000
    depends_on:
      - backend
    networks:
      - sayur-network

networks:
  sayur-network:

volumes:
  mysql-data:
